In [5]:
import pandas as pd
df= pd.read_csv("../data/airline_route_profitability.csv")
df.shape

(7974, 33)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7974 entries, 0 to 7973
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Flight_Number            7974 non-null   str
 1   Flight_Date              7974 non-null   str
 2   Origin                   7974 non-null   str
 3   Destination              7974 non-null   str
 4   Route                    7974 non-null   str
 5   Aircraft_Type            7974 non-null   str
 6   Aircraft_Capacity        7974 non-null   int64
 7   Passengers               7974 non-null   int64
 8   Load_Factor              7974 non-null   float64
 9   Flight_Hours             7974 non-null   float64
 10  Season                   7974 non-null   str
 11  Route_Category           7974 non-null   str
 12  Demand_Level             7974 non-null   str
 13  Ticket_Revenue           7974 non-null   float64
 14  Ancillary_Revenue        7703 non-null   float64
 15  Total_Revenue            7974 non-null   float64
 16  Fuel_Cost                7974 non-null   float64
 17  Maintenance_Cost         7974 non-null   float64
 18  Crew_Cost                7974 non-null   float64
 19  Depreciation_Cost        7974 non-null   float64
 20  Insurance_Cost           7974 non-null   float64
 21  Airport_Fees             7974 non-null   float64
 22  Catering_Cost            7709 non-null   float64
 23  Handling_Cost            7718 non-null   float64
 24  Navigation_Fees          7974 non-null   float64
 25  Sales_Distribution_Cost  7974 non-null   float64
 26  Passenger_Service_Cost   7974 non-null   float64
 27  Overhead_Cost            7974 non-null   float64
 28  Marketing_Cost           7974 non-null   float64
 29  IT_Systems_Cost          7974 non-null   float64
 30  Total_Cost               7974 non-null   float64
 31  Profit                   7974 non-null   float64
 32  Profit_Margin            7974 non-null   float64
dtypes: float64(22), int64(2), str(9)
memory usage: 2.5 MB

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Aircraft_Capacity,7974.0,317.800602,98.768543,180.0000,296.000000,325.0000,396.0000,517.00
Passengers,7974.0,254.819162,88.141968,104.0000,180.250000,246.0000,302.0000,491.00
Load_Factor,7974.0,0.801570,0.087755,0.5766,0.736825,0.8015,0.8731,0.95
Flight_Hours,7974.0,6.327314,4.555668,1.2000,3.200000,4.5000,7.5000,16.50
Ticket_Revenue,7974.0,264383.873745,237102.214088,14812.3400,56429.512500,182620.3550,412696.9325,1303644.62
Ancillary_Revenue,7703.0,33073.717197,30167.518230,1616.6200,7234.405000,22842.8500,51234.9750,192921.91
Total_Revenue,7974.0,297436.197695,266832.892069,16650.0200,63502.390000,204812.5900,463800.2450,1496566.53
Fuel_Cost,7974.0,46296.405878,43123.036900,2592.6200,16137.575000,28344.9500,74832.9600,191047.78
Maintenance_Cost,7974.0,18973.224856,17677.194300,1380.0000,7040.000000,11200.0000,30800.0000,72500.00
Crew_Cost,7974.0,8905.116880,7414.772748,936.0000,3840.000000,5850.0000,13000.0000,29000.00
Depreciation_Cost,7974.0,25258.814898,22152.943693,2040.0000,10240.000000,15750.0000,39000.0000,87000.00
Insurance_Cost,7974.0,4504.945699,3872.411136,336.0000,1920.000000,2925.0000,6800.0000,14500.00
Airport_Fees,7974.0,5054.911403,2492.832311,2000.7900,3197.342500,4335.7550,6562.8550,11998.99
Catering_Cost,7709.0,5998.747912,2729.957117,1398.4000,3962.540000,5504.9100,7494.6800,17079.70
Handling_Cost,7718.0,3988.998616,1146.741218,2000.0400,2991.377500,3971.8350,4974.3150,5999.98
Navigation_Fees,7974.0,3785.569431,2861.881472,483.5700,1602.465000,2879.2900,5084.8950,13166.36
Sales_Distribution_Cost,7974.0,44659.242364,40575.117395,2143.1100,9690.980000,31167.8450,68973.7125,222595.18
Passenger_Service_Cost,7974.0,5721.982070,2295.208112,1750.1100,4002.195000,5386.0700,7018.9725,14601.28
Overhead_Cost,7974.0,35742.265706,29368.802114,3750.1900,13955.147500,24366.9450,54205.3425,144736.04
Marketing_Cost,7974.0,13448.184059,12633.987523,608.6200,2942.397500,9235.8700,20226.5275,78018.07
IT_Systems_Cost,7974.0,2930.738501,1154.464363,923.2600,2063.495000,2772.2700,3576.7950,7354.16
Total_Cost,7974.0,225266.563756,174526.327680,28019.3800,83612.367500,154808.3550,355441.0025,835108.70
Profit,7974.0,72169.633934,138692.750890,-250914.8500,-9052.485000,21326.0550,116046.0900,972133.76
Profit_Margin,7974.0,6.190222,39.040588,-236.2700,-10.747500,15.2150,33.2800,64.96

In [8]:
df.isnull().sum()

Flight_Number                0
Flight_Date                  0
Origin                       0
Destination                  0
Route                        0
Aircraft_Type                0
Aircraft_Capacity            0
Passengers                   0
Load_Factor                  0
Flight_Hours                 0
Season                       0
Route_Category               0
Demand_Level                 0
Ticket_Revenue               0
Ancillary_Revenue          271
Total_Revenue                0
Fuel_Cost                    0
Maintenance_Cost             0
Crew_Cost                    0
Depreciation_Cost            0
Insurance_Cost               0
Airport_Fees                 0
Catering_Cost              265
Handling_Cost              256
Navigation_Fees              0
Sales_Distribution_Cost      0
Passenger_Service_Cost       0
Overhead_Cost                0
Marketing_Cost               0
IT_Systems_Cost              0
Total_Cost                   0
Profit                       0
Profit_Margin                0
dtype: int64

In [9]:
df["Flight_Date"] = pd.to_datetime(df["Flight_Date"])
df["Flight_Date"].min(),df["Flight_Date"].max()

(Timestamp('2024-01-01 00:00:00'), Timestamp('2024-12-31 00:00:00'))

In [10]:
df.nunique().sort_values(ascending=False)

Flight_Number              7974
Total_Revenue              7974
Total_Cost                 7974
Ticket_Revenue             7973
Profit                     7972
Sales_Distribution_Cost    7970
Overhead_Cost              7968
Fuel_Cost                  7960
Marketing_Cost             7956
Passenger_Service_Cost     7934
Navigation_Fees            7931
Airport_Fees               7915
IT_Systems_Cost            7892
Ancillary_Revenue          7695
Catering_Cost              7686
Handling_Cost              7647
Profit_Margin              5692
Load_Factor                2959
Passengers                  388
Flight_Date                 366
Maintenance_Cost             54
Insurance_Cost               54
Crew_Cost                    53
Depreciation_Cost            51
Destination                  30
Route                        30
Flight_Hours                 21
Aircraft_Type                 6
Aircraft_Capacity             6
Season                        4
Route_Category                3
Demand_Level                  2
Origin                        1
dtype: int64

In [11]:
df["Profit_Margin"].describe()

count    7974.000000
mean        6.190222
std        39.040588
min      -236.270000
25%       -10.747500
50%        15.215000
75%        33.280000
max        64.960000
Name: Profit_Margin, dtype: float64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["Flight_Number"].duplicated().sum()

np.int64(0)

In [14]:
print("Passengers > Capacity:", (df["Passengers"] > df["Aircraft_Capacity"]).sum())
print("Load Factor outside 0-1:", ((df["Load_Factor"] < 0) | (df["Load_Factor"] > 1)).sum())
print("Negative Revenue:", (df["Total_Revenue"] < 0).sum())
print("Negative Cost:", (df["Total_Cost"] < 0).sum())

Passengers > Capacity: 0
Load Factor outside 0-1: 0
Negative Revenue: 0
Negative Cost: 0

In [15]:
profit_check = df["Total_Revenue"] - df["Total_Cost"]

(profit_check - df["Profit"]).abs().describe()

count    7.974000e+03
mean     2.427891e-03
std      4.287955e-03
min      0.000000e+00
25%      1.818989e-12
50%      1.455192e-11
75%      8.731149e-11
max      1.000000e-02
dtype: float64

In [16]:
margin_check = (df["Profit"] / df["Total_Revenue"]) * 100

(df["Profit_Margin"] - margin_check).abs().describe()

count    7974.000000
mean        0.002523
std         0.001439
min         0.000001
25%         0.001259
50%         0.002555
75%         0.003762
max         0.005011
dtype: float64

In [17]:
df.duplicated().sum()

np.int64(0)

In [20]:
margin_check = (df["Profit"] / df["Total_Revenue"]) * 100

In [21]:
df[["Ancillary_Revenue", "Catering_Cost", "Handling_Cost"]].isnull().sum()

Ancillary_Revenue    271
Catering_Cost        265
Handling_Cost        256
dtype: int64

In [22]:
margin_check

0       -9.091503
1       24.611952
2       58.585606
3       20.905117
4      -27.539119
          ...
7969    44.884430
7970    16.393998
7971    24.447568
7972     2.015632
7973    -5.001336
Length: 7974, dtype: float64

In [23]:
df[df["Ancillary_Revenue"].isnull()][
    ["Flight_Number", "Route", "Passengers", "Ticket_Revenue",
     "Ancillary_Revenue", "Total_Revenue"]
].head(10)

,Flight_Number,Route,Passengers,Ticket_Revenue,Ancillary_Revenue,Total_Revenue
37,EK3680,DXB-MCT,161,40122.27,NaN,45153.23
49,EK1518,DXB-HKG,488,799643.40,NaN,918891.60
97,EK1318,DXB-HYD,270,171255.87,NaN,192046.01
109,EK2297,DXB-LAX,246,385302.49,NaN,434553.81
117,EK8691,DXB-CMB,280,193789.09,NaN,222553.79
119,EK6789,DXB-SIN,447,829234.07,NaN,920361.30
126,EK2803,DXB-SIN,340,714749.00,NaN,789077.35
211,EK8218,DXB-CDG,438,698320.04,NaN,792986.52
216,EK8548,DXB-IST,297,183276.26,NaN,201999.93
257,EK4114,DXB-MEL,277,346054.30,NaN,393497.42

In [24]:
df["Ancillary_Revenue"].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
7969     True
7970    False
7971    False
7972    False
7973    False
Name: Ancillary_Revenue, Length: 7974, dtype: bool

In [27]:
df["implied_ancillary"] = df["Total_Revenue"] - df["Ticket_Revenue"]

(df["implied_ancillary"] - df["Ancillary_Revenue"]).abs().describe()

count    7.703000e+03
mean     2.434117e-03
std      4.291694e-03
min      0.000000e+00
25%      3.637979e-12
50%      1.455192e-11
75%      9.822543e-11
max      1.000000e-02
dtype: float64

In [28]:
missing_ancillary = df["Ancillary_Revenue"].isnull()

df.loc[missing_ancillary, "Total_Revenue"].sub(
    df.loc[missing_ancillary, "Ticket_Revenue"]
).describe()

count       271.000000
mean      32444.238819
std       29210.839320
min        1994.730000
25%        7811.775000
50%       20790.140000
75%       49239.110000
max      133280.110000
dtype: float64

In [29]:
df["Ancillary_Revenue"].isnull().sum()

np.int64(271)

In [31]:
df["Ancillary_Revenue"] = df["Ancillary_Revenue"].fillna(
    df["Total_Revenue"] - df["Ticket_Revenue"]
)

In [32]:
df["Ancillary_Revenue"].isnull().sum()

np.int64(0)

In [33]:
df[df["Catering_Cost"].isnull()][
    ["Flight_Number", "Route", "Passengers",
     "Total_Cost", "Catering_Cost"]
].head(10)

    Flight_Number    Route  Passengers  Total_Cost  Catering_Cost
14         EK5478  DXB-HKG         298   388671.45            NaN
72         EK1503  DXB-HKG         491   546545.82            NaN
135        EK7535  DXB-CDG         356   350695.94            NaN
169        EK2010  DXB-MAA         254   131414.58            NaN
170        EK4299  DXB-SFO         243   412576.00            NaN
237        EK7377  DXB-JFK         460   771314.50            NaN
270        EK6736  DXB-SYD         409   640695.21            NaN
277        EK1996  DXB-MAA         279   144439.92            NaN
459        EK4779  DXB-MEL         286   422947.98            NaN
471        EK7995  DXB-LHE         253   125672.68            NaN